package fr.cdlja.weebsport.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLineAllPropertiesEquals(Line expected, Line actual) {
        assertLineAutoGeneratedPropertiesEquals(expected, actual);
        assertLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLineAllUpdatablePropertiesEquals(Line expected, Line actual) {
        assertLineUpdatableFieldsEquals(expected, actual);
        assertLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLineAutoGeneratedPropertiesEquals(Line expected, Line actual) {
        assertThat(expected)
            .as("Verify Line auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLineUpdatableFieldsEquals(Line expected, Line actual) {
        assertThat(expected)
            .as("Verify Line relevant properties")
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLineUpdatableRelationshipsEquals(Line expected, Line actual) {
        assertThat(expected)
            .as("Verify Line relationships")
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }
}
