# This is a basic workflow that is manually triggered

name: CI Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prettier-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Node packages
        run: npm install
      - name: Prettify Code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: '--write **/*.{html,ts,json,css,java}'
      - name: Linter Code
        run: |
            cd src 
            npm run lint
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and run tests
        run: ./mvnw clean verify
      
